server:
  port: 8082

spring:
  application:
    name: DEPARTMENT-SERVICE
  data:
    mongodb:
      port: 27017
      host: localhost
      database: departmentService




logging:
  file:
    name: /Users/kuldeepsingh/Desktop/project/microservice/log/services.log